In [30]:
!wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt


--2024-04-11 13:34:01--  https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
Loaded CA certificate '/usr/ssl/certs/ca-bundle.crt'
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.108.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1115394 (1.1M) [text/plain]
Saving to: 'input.txt.3'

     0K .......... .......... .......... .......... ..........  4% 7.93M 0s
    50K .......... .......... .......... .......... ..........  9% 7.37M 0s
   100K .......... .......... .......... .......... .......... 13% 26.2M 0s
   150K .......... .......... .......... .......... .......... 18% 22.4M 0s
   200K .......... .......... .......... .......... .......... 22% 10.5M 0s
   250K .......... .......... .......... .......... .......... 27% 23.9M 0s
   300K .......... .......... .......... .

In [27]:
!curl -X GET \ "https://datasets-server.huggingface.co/rows?dataset=davanstrien%2FHaiku_Dataset&config=default&split=train&offset=0&length=100"

{"features":[{"feature_idx":0,"name":"haiku","type":{"dtype":"string","_type":"Value"}},{"feature_idx":1,"name":"source","type":{"dtype":"string","_type":"Value"}}],"rows":[{"row_idx":0,"row":{"haiku":"fishing boats\ncolors of\nthe rainbow","source":"tempslibres"},"truncated_cells":[]},{"row_idx":1,"row":{"haiku":"ash wednesday--\ntrying to remember \nmy dream","source":"tempslibres"},"truncated_cells":[]},{"row_idx":2,"row":{"haiku":"snowy morn--\npouring another cup\nof black coffee","source":"tempslibres"},"truncated_cells":[]},{"row_idx":3,"row":{"haiku":"shortest day\nflames dance\nin the oven","source":"tempslibres"},"truncated_cells":[]},{"row_idx":4,"row":{"haiku":"haze\nhalf the horse hidden\nbehind the house","source":"tempslibres"},"truncated_cells":[]},{"row_idx":5,"row":{"haiku":"low sun\nthe lady in red\non high heels","source":"tempslibres"},"truncated_cells":[]},{"row_idx":6,"row":{"haiku":"advent\nthe passing stranger\nfarts","source":"tempslibres"},"truncated_cells":[

curl: (3) URL rejected: Bad hostname
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100 12871  100 12871    0     0   5558      0  0:00:02  0:00:02 --:--:--  5562


In [28]:
!curl -X GET \
     "https://huggingface.co/api/datasets/davanstrien/Haiku_Dataset/parquet/default/train"

["https://huggingface.co/api/datasets/davanstrien/Haiku_Dataset/parquet/default/train/0.parquet"]


  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    97  100    97    0     0     75      0  0:00:01  0:00:01 --:--:--    75
100    97  100    97    0     0     75      0  0:00:01  0:00:01 --:--:--    75


In [19]:
inputnew.txt

NameError: name 'inputnew' is not defined

In [31]:
with open('input.txt', 'r') as file:
    content = file.read()


In [32]:
with open('input.txt','r',encoding='utf-8') as f:
    text = f.read()
print("dataset charlen : " , len(text))

dataset charlen :  1115394


In [7]:
#first 1000 characters, includes spaces as well
print(text[:1000])

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You are all resolved rather to die than to famish?

All:
Resolved. resolved.

First Citizen:
First, you know Caius Marcius is chief enemy to the people.

All:
We know't, we know't.

First Citizen:
Let us kill him, and we'll have corn at our own price.
Is't a verdict?

All:
No more talking on't; let it be done: away, away!

Second Citizen:
One word, good citizens.

First Citizen:
We are accounted poor citizens, the patricians good.
What authority surfeits on would relieve us: if they
would yield us but the superfluity, while it were
wholesome, we might guess they relieved us humanely;
but they think we are too dear: the leanness that
afflicts us, the object of our misery, is as an
inventory to particularise their abundance; our
sufferance is a gain to them Let us revenge this with
our pikes, ere we become rakes: for the gods know I
speak this in hunger for bread, not in thirst for revenge.



In [11]:
##to note , text is just the collection of characters of the dataset in order of their appearance
##if we create a set of (text) we will get all the characters in order of their appearnace but all of them would be unique(characters, not words , so it wont make sense)
##if we make a list out of those sets then its content and orientation remains same ,just now it behaves as a list rather than a set
##if we sort that list it will display all unique characters of "text" in alphabetical order 
chars = sorted(list(set(text)))
vocab_size =len(chars)
print((chars))
print("".join(chars))#joins all individual chars from list into a single string 
print(vocab_size)

['\n', ' ', '!', '$', '&', "'", ',', '-', '.', '3', ':', ';', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']

 !$&',-.3:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
65


In [26]:
##creating a character mapping from characters to integers, basically encodinga and decoding our characters
stoi = {ch:i for i , ch in enumerate(chars)}##string to int
itos = {i:ch for i,ch in enumerate(chars)}
encode = lambda s: [stoi[c] for c in s] ##encoding operation, string input encoded int output
decode  = lambda l: ''.join([itos[i] for i in l])# decoding operation ,takes encoded int input and decodes it by outputting decoded string
print (encode("my name is yatharth"))
##any element in encode, in this scenario , cant be greater than 64
trylist = [51, 63, 1, 52, 39, 51, 43, 1]
trylist2 = [46, 47, 1, 58, 46, 43, 56, 64]
print(encode("hi there"))
print (decode(trylist2))
##the above is an example of character level tokenizer where each encoding element is responsible for change in a character , in general people use sub-word encoding for stronger encoding 
##the simplicity of this encoder results in a relatively long encoded list 

[51, 63, 1, 52, 39, 51, 43, 1, 47, 57, 1, 63, 39, 58, 46, 39, 56, 58, 46]
[46, 47, 1, 58, 46, 43, 56, 43]
hi therz


In [27]:
##now we use our encoder to encode out "text"
import torch 
data = torch.tensor(encode(text),dtype = torch.long)
print (data.shape , data.dtype)
print (data[:1000]) #viewing the 1st 1000 data encodings 

torch.Size([1115394]) torch.int64
tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44,
        53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39, 52, 63,
         1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1, 51, 43,  1,
        57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31, 54, 43, 39, 49,
         6,  1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56, 57, 58,  1, 15, 47,
        58, 47, 64, 43, 52, 10,  0, 37, 53, 59,  1, 39, 56, 43,  1, 39, 50, 50,
         1, 56, 43, 57, 53, 50, 60, 43, 42,  1, 56, 39, 58, 46, 43, 56,  1, 58,
        53,  1, 42, 47, 43,  1, 58, 46, 39, 52,  1, 58, 53,  1, 44, 39, 51, 47,
        57, 46, 12,  0,  0, 13, 50, 50, 10,  0, 30, 43, 57, 53, 50, 60, 43, 42,
         8,  1, 56, 43, 57, 53, 50, 60, 43, 42,  8,  0,  0, 18, 47, 56, 57, 58,
         1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 18, 47, 56, 57, 58,  6,  1, 63,
        53, 59,  1, 49, 52, 53, 61,  1, 15, 39, 47, 59, 57,  1, 25, 39, 56, 41,
      

In [34]:
##now we will split the data into training and validation 
n = int(0.9*len(data))
train_data= data[:n]
val_data= data[n:]

In [33]:
block_size = 8
train_data [:block_size+1]
x = train_data[:block_size]
y = train_data[1:block_size+1]
print(x)
print(y)
print(train_data[:block_size+1])
for t in range(block_size):
    context = x[:t+1]
    target=y[t]
    print(f"When input is {context} the targe : {target}")
###here in a sense the block_Size determines the size of the context window , and
### x and y determine the context and target pairss, in lay man terms they help machine understand what action to take based on present circumstane 

    

tensor([18, 47, 56, 57, 58,  1, 15, 47])
tensor([47, 56, 57, 58,  1, 15, 47, 58])
tensor([18, 47, 56, 57, 58,  1, 15, 47, 58])
When input is tensor([18]) the targe : 47
When input is tensor([18, 47]) the targe : 56
When input is tensor([18, 47, 56]) the targe : 57
When input is tensor([18, 47, 56, 57]) the targe : 58
When input is tensor([18, 47, 56, 57, 58]) the targe : 1
When input is tensor([18, 47, 56, 57, 58,  1]) the targe : 15
When input is tensor([18, 47, 56, 57, 58,  1, 15]) the targe : 47
When input is tensor([18, 47, 56, 57, 58,  1, 15, 47]) the targe : 58


In [36]:
torch.manual_seed(1337)
batch_size = 4 #how many independant sequences will we process in parallel
block_size = 8 # what is the context length for predictions

def get_batch(split):
    #generate a small baatch of data of input x and targets y 
    data = train_data if split =='train' else val_data
    ix = torch.randint (len(data)-block_size, (batch_size,))
    ##using torch.stack to make a matrix out of the rows ix
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x ,y

xb, yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

print('---')

for b in range (batch_size): 
    for t in range (block_size):
        context = xb[b, :t+1]
        target = yb[b,t]
        ####here b,t indexing denotes which block of which batch we are currently iterating 
        print (f"when input is {context.tolist()} the target: {target}")
##the 4 by 8 tensor naturally contains 4*8=32 examples, and they are completely independant as far as the transformer is concerned
 

inputs:
torch.Size([4, 8])
tensor([[24, 43, 58,  5, 57,  1, 46, 43],
        [44, 53, 56,  1, 58, 46, 39, 58],
        [52, 58,  1, 58, 46, 39, 58,  1],
        [25, 17, 27, 10,  0, 21,  1, 54]])
targets:
torch.Size([4, 8])
tensor([[43, 58,  5, 57,  1, 46, 43, 39],
        [53, 56,  1, 58, 46, 39, 58,  1],
        [58,  1, 58, 46, 39, 58,  1, 46],
        [17, 27, 10,  0, 21,  1, 54, 39]])
---
when input is [24] the target: 43
when input is [24, 43] the target: 58
when input is [24, 43, 58] the target: 5
when input is [24, 43, 58, 5] the target: 57
when input is [24, 43, 58, 5, 57] the target: 1
when input is [24, 43, 58, 5, 57, 1] the target: 46
when input is [24, 43, 58, 5, 57, 1, 46] the target: 43
when input is [24, 43, 58, 5, 57, 1, 46, 43] the target: 39
when input is [44] the target: 53
when input is [44, 53] the target: 56
when input is [44, 53, 56] the target: 1
when input is [44, 53, 56, 1] the target: 58
when input is [44, 53, 56, 1, 58] the target: 46
when input is [44, 53,

In [37]:
print(xb)

tensor([[24, 43, 58,  5, 57,  1, 46, 43],
        [44, 53, 56,  1, 58, 46, 39, 58],
        [52, 58,  1, 58, 46, 39, 58,  1],
        [25, 17, 27, 10,  0, 21,  1, 54]])


In [96]:
##now that we have an adequate input we will feed it into a neural network which acts as our model
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)
##using the bigram language model , see reference later
class mymodel1(nn.Module):
    def __init__ (self, vocab_size):
        super().__init__()
        #each token directly reads off the logits for the next token from a lookup table 
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)
        
    def forward(self, idx, targets=None):
        #idx and targets are both (B,T) tensor of integers 
        logits = self.token_embedding_table(idx) #(B,T,C)
        ## pytorch is going to convert this into a batch(4) by time(8) by channel(vocab_Size=65) tensor
        ##it is important to note that we will have to change the dimensions of our logits from B/T/C to B*T/C because this is the format the functional cross entropy expects it to be in 
        if targets is None:
            loss=None
        else:
                
            B,T,C = logits .shape
            #changing dimensions of logits 
            logits = logits.view(B*T,C)
            targets = targets.view(B*T)
            #if second dim of 2-d matrix not provided in view, it is assumed to remove error possibillity 
            
            loss = F.cross_entropy(logits, targets)
            ##compares quality of logits wrt targets 
        
        return logits, loss 
        ###in essence we are predicting what comes next based on the single identity of a token
        ##a brief understanding of how the model functions so far would be taht we have created an embedding table which is a sqaure matrix of size = vocab_size
        ## here each embedding will refer to it when invoked using idx and "pluck out" the row that has the same value as itself , i.e. element 24 will pluck out the 24th row of the table 
        ## now we will create the generate part of the model
    def generate(self, idx, max_new_tokens):
        #idx is (B,T) array of indices in the current context 
        for _ in range(max_new_tokens): 
            #get_prediction
            logits, loss = self(idx)
            #focus only on the last time step
            logits = logits[:,-1,:] #becomes (B,C)
            ##applying softmax on logits to get probabillities 
            probs =F.softmax(logits,dim=-1)#(B,C)
            ##sample from the distribution 
            ##
            idx_next = torch.multinomial(probs, num_samples=1) #(B,1) for each batch we have a single prediction for what comes next 
            
            #append sampled index into the running sequence 
            idx = torch.cat((idx, idx_next) ,dim=1) #(B,T+1)
            ##above we can see that whatever is predicted is concatenated to the prvious idx to continue flow of text generation 
            
        return idx 

m = mymodel1(vocab_size)
logits,loss = m(xb,yb)
print(logits.shape)
print(loss)
##the line below decodes the encoded elements on a per batch basis , it will be garbage for now because we havent trained our model yet 
print(decode(m.generate(idx= torch.zeros((1,1),dtype = torch.long),max_new_tokens=100)[0].tolist()))     

torch.Size([32, 65])
tensor(4.8829, grad_fn=<NllLossBackward0>)

Sr?qP-QWktXoL&jLDJgOLVz'RIoDqHdhsV&vLLxatjscMpwLERSPyao.qfzs$Ys$zF-w,;eEkzxjgCKFChs!iWW.ObzDnxA Ms$3


In [121]:
#creating pytorch optimizing object 
optimizer = torch.optim.Adam(m.parameters(), lr=1e-3)
##now for the training loop 
epochs=1000
loss_array = []
for steps in range (epochs):
    xb ,yb = get_batch('train')
    #evaluate the loss
    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()
    loss_array.append(loss.item())
    
print(loss.item())
    

    

2.0508344173431396


In [125]:
print(decode(m.generate(idx= torch.zeros((1,1),dtype = torch.long),max_new_tokens=1001)[0].tolist()))     


ARE:

THay mee gantive an mputis t cl, wnthyont?
Anthecomy, angrrid l ht t mund r fortharet he haraderoy youre.
Tan
Who ndedyo te Bun:
EDWhe f ld t malender, ce s can, qustas, ag r, in nd obllouthouche menonsewim yon hesowetwonese RENostoup Y herin, thes covengharothome areasall fer toitolis avis rd wawakeast gor thaverindavet we y coran,
LULIOLORI awispt a amith wito ss w,

LA: arne.


MIINCHes,

He,
T:
Hath toreat'siss haut t pane.
S:

RD:
Wicanes mer il ougho shifo t,
Meed d s t t ad
Aspome ha nd thonthoueren,
LE:
YWind be, stelalea matr aved
Fof hthe; higlf yo fee ayat thind myowelllotowiner d clinetherse front, lle?
Angr boucancemin bous holdaid t llinchithe nde
ARD VON amurds se,
S:
Anatoreshow g fout on.
Thth he, tod nghe,
S:
INGard loffre.
Be?
AR:
Y:
MEESiourl buto athaithe an, d t tt malloan. ff thes he.
Fofent exf d rte mise Gompaile mabe aveno tly hethabr dutorl beveso,
IONo ge:
I'than offlleveat om yoformouno h appordoulore forat VO:
Bur h l meeve

I'eness s tisprincoit, a

##we have completed above the most simple iteration of the model , now with improving model complexity we will see improvement in content 

self attention application
to improve our output we can say that improving communication between tokens is key , but the communication should make sense
the current token should only be able to communicate with the previous tokens and not the future tokens, becase they virtually dont exist yet and we need to predict those tokens 
easiest way for tokens to talk to each other is to take the average of the past steps , as it will summarize the current token with context to its history 


the concept of self attention was introduced in the gpt paper "attention is all you need " 
it introduced the transformer model for the first time ,which was a novel architecture that was significantly different from RNN which was dominant in that era 

key innovation of transformers was the use of self-attention mechanism.
RNNs process data sequentially , but transformers were able to process data parallelly which significantly brought down the training time and improved the handling of long range dependencies in text 


The concept of self attention can be explained in detail as follows : 
input to the self attention layer is aset of vectors 
each vector represents a word or a token in the input sequence 

these vectors are typically the output of an embedding/encoding layer

query , key , value : for each tokens vector , the self attention mechanism creates three different vectors through learnedd linear transformations
these vectors are termed as Query(Q ) , Key (K) and Value(V) the transformations for these are seperate for each vector but are teh same across different positions 

attention scores : to determine the amount of attention eaach element is giving to other element,  the dot product is calculated between the query vector of each position and keey vector of every other position. 
this results in a score that signifies how much focus to put on other parts of the input sequence when encoding a particular part 

these scores are then scaled down for stabillity 

softmax is applied to these scores to obtain weights of the attention 

weighted sum : the value vectors are then weighted according to these softmax scores . this represents parts of the input sequence that are importatnt to the current token
output for each position is the aggregation of these weighted value vectors ,this output then further passes throught further layers 


The Bag of Words (BoW) model is a simple yet influential method in natural language processing and machine learning for text representation. It's used in various tasks like document classification, sentiment analysis, and information retrieval. The fundamental idea of the BoW model is to represent text data as a bag (multiset) of words without considering grammar or word order but maintaining multiplicity.

Here's how the Bag of Words model typically works:

Vocabulary Creation: First, a vocabulary of all unique words across all documents in the training set is created. Each word in the vocabulary is assigned a unique index.

Document Representation: Each document (or text snippet) is then represented as a vector. The length of this vector is equal to the length of the vocabulary.

Word Counting: The simplest way to fill in this vector is by counting the occurrences of each word from the vocabulary in the document. Each position in the vector corresponds to a word in the vocabulary, and the value at that position is the count of that word in the document. This method is known as "Term Frequency".

Alternatives to Simple Counts: Instead of simple word counts, variants like TF-IDF (Term Frequency-Inverse Document Frequency) can be used. TF-IDF weighs the word counts by a measure of how common or rare they are across all documents, which helps in reducing the impact of frequently occurring words that might be less informative.

Handling Unseen Words: If a new document contains words not seen in the training set, these words are typically ignored, as the model doesn't have any information on them.

Advantages of the Bag of Words model:

Simplicity: It's straightforward to understand and implement.
Efficiency: Conversion of text to a numerical form that machine learning algorithms can work with is efficient.
Effectiveness: For many tasks, especially with sufficient data, it provides a good baseline performance.


Limitations:

Loss of Context and Order: Since it treats text as a 'bag' (set) of words, the order and structure of the words are lost, which can be critical in understanding linguistic nuances.
Sparsity: The resulting vectors are typically high-dimensional and sparse, which can be inefficient for computation.
Vocabulary Size: The size of the vocabulary can become very large for large datasets, leading to high memory consumption.
Word Sense Disambiguation: It doesn't handle different meanings of the same word (homonyms) well.

In [126]:
torch.manual_seed(1337)
B,T,C = 4,8,2 #batch, time, channels
x = torch.randn(B,T,C)
x.shape


torch.Size([4, 8, 2])

In [145]:
# we want x[b,t] = mean_{i<=t} x[b,i]
xbow = torch.zeros((B,T,C)) ## here bow is added to represent bag of words
for b in range (B):
    for t in range (T):
        xprev = x[b,:t+1] #(t,C)
        xbow[b,t] = torch.mean(xprev,0)
        
        

In [142]:
x[0]


tensor([[ 0.1808, -0.0700],
        [-0.3596, -0.9152],
        [ 0.6258,  0.0255],
        [ 0.9545,  0.0643],
        [ 0.3612,  1.1679],
        [-1.3499, -0.5102],
        [ 0.2360, -0.2398],
        [-0.9211,  1.5433]])

In [146]:
xbow[0]

tensor([[ 0.1808, -0.0700],
        [-0.0894, -0.4926],
        [ 0.1490, -0.3199],
        [ 0.3504, -0.2238],
        [ 0.3525,  0.0545],
        [ 0.0688, -0.0396],
        [ 0.0927, -0.0682],
        [-0.0341,  0.1332]])

In [ ]:
##to print lower and upper  triangular matrix:
print(torch.tril(torch.ones(3,3)))
torch.triu(torch.ones(3,3))

In [138]:
##we can see how xbow is a mean of the terms in x at current index and all previous indices (thats why 1st term of both are same )
##the above method was working but was inefficient , we can increase efficiency by matrix multiplication 
##it can be acheived by seeing an example below : 
torch.manual_seed(42)
a = torch.tril(torch.ones(3,3))
a =a/torch.sum(a,1,keepdim=True)
b = torch.randint(0,10,(3,2)).float()
c = a@b
print('a=')
print(a)
print("_____________________")
print("b=")
print(b)
print("________________________")
print("c=")
print(c)
print("________________________")
##as wecan see using this technique it is possible to find out the historical average that is to be used by the bag of words 


a=
tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])
_____________________
b=
tensor([[2., 7.],
        [6., 4.],
        [6., 5.]])
________________________
c=
tensor([[2.0000, 7.0000],
        [4.0000, 5.5000],
        [4.6667, 5.3333]])
________________________


In [149]:
#implementing above method for xbow
wei = torch.tril(torch.ones(T,T))
wei = wei/wei.sum(1,keepdim=True)
xbow2 = wei @ x 
##to check if xbow= xbow2 ,since xbow2 serves the same purpose but was just created using a more efficient method 
print(xbow)
print(xbow2)
torch.allclose(xbow, xbow2)


tensor([[[ 0.1808, -0.0700],
         [-0.0894, -0.4926],
         [ 0.1490, -0.3199],
         [ 0.3504, -0.2238],
         [ 0.3525,  0.0545],
         [ 0.0688, -0.0396],
         [ 0.0927, -0.0682],
         [-0.0341,  0.1332]],

        [[ 1.3488, -0.1396],
         [ 0.8173,  0.4127],
         [-0.1342,  0.4395],
         [ 0.2711,  0.4774],
         [ 0.2421,  0.0694],
         [ 0.0084,  0.0020],
         [ 0.0712, -0.1128],
         [ 0.2527,  0.2149]],

        [[-0.6631, -0.2513],
         [ 0.1735, -0.0649],
         [ 0.1685,  0.3348],
         [-0.1621,  0.1765],
         [-0.2312, -0.0436],
         [-0.1015, -0.2855],
         [-0.2593, -0.1630],
         [-0.3015, -0.2293]],

        [[ 1.6455, -0.8030],
         [ 1.4985, -0.5395],
         [ 0.4954,  0.3420],
         [ 1.0623, -0.1802],
         [ 1.1401, -0.4462],
         [ 1.0870, -0.4071],
         [ 1.0430, -0.1299],
         [ 1.1138, -0.1641]]])
tensor([[[ 0.1808, -0.0700],
         [-0.0894, -0.4926],
      

False

In [152]:
##3rd version
tril = torch.tril(torch.ones(T,T))
wei = torch.zeros((T,T))
wei = wei.masked_fill(tril==0, float('-inf'))
wei = F.softmax(wei,dim=-1)
xbow3 = wei@x
torch.allclose(xbow2,xbow3)

True

In [153]:
#version 4 : self attention 
torch.manual_seed(1337)
B,T,C = 4,8 ,32 ##batch, time , channels 
x = torch.randn(B,T,C)
##we are now witnessing a single head perform self attention 
head_size = 16 
##AS written earlier we will multiply key and query as their dot product to get an attention score
key = nn.Linear(C, head_size, bias=False)
query = nn.Linear(C, head_size, bias=False)
value = nn.Linear(C, head_size , bias=False)

k = key(x)
q =query(x)
wei = q@k.transpose(-2,-1) #(B,T,16) @ (B,16,T) ----> (B,T,T)
tril = torch.tril(torch.ones(T,T))

wei = wei.masked_fill(tril==0,float('-inf'))
##we have to mask the future tokens in order to prevent notes from the present communicating with notes of the future 
wei = F.softmax(wei, dim=-1)
##we dont aggregate the token x , we aggregate the value v
v = value(x) 
out = wei @v 
out.shape
#self attention called self attention cause all 3 attributes that are keys, queries and values all come from the same token x 

torch.Size([4, 8, 16])

Notes: 
attention is a communication mechanism. it can be imagined as nodes of a directed graph looking at each other and aggregating information witha  weighted sum from all nodes taht point to them ,with data-dependent weights 
There is no notion of space , Attention simply acts over a set of vectors . This is why we need to positionally encode tokens
Each example across batch dimension is of course processed completely independently and never "talk" to each other 
In an encoder attention block just delete the single line that does masking with tril, allowing all tokens to communicate.This block here is called a "decoder" attention block because it has triangular masking , and is usually used in autoregressive settings , like language modelling 
self attention just means that the keys and values are produced from the same sources as queries. In "cross-attention" , the queries still get produced  from x ,but the keys and values  come from some other ,external source (e.g. an encoder module ) 

scaled attention additional divides wei by 1/sqrt(head_size). this makes it so when input Q,K are unit variance , wei will be unit vairance as well , ans Softmax will stay diffused and not saturate too much . Illustration below 


In [155]:
k = torch.randn(B,T,head_size)
q = torch.randn(B,T,head_size)
wei= q@k.transpose(-2,-1)*head_size** -0.5


In [157]:
print(k.var())
print(q.var())
print(wei.var())

tensor(1.0449)
tensor(1.0700)
tensor(1.0918)


In [158]:
torch.softmax(torch.tensor([0.1,-0.2,0.3,-0.2,0.5]),dim=-1)


tensor([0.1925, 0.1426, 0.2351, 0.1426, 0.2872])

In [159]:
torch.softmax(torch.tensor([0.1,-0.2,0.3,-0.2,0.5])*8,dim=-1)


tensor([0.0326, 0.0030, 0.1615, 0.0030, 0.8000])

In [160]:
#applying multi-head attention 
torch.cuda.is_available()

False

In [ ]:
from agent import BaseAgent
import random

class Agent(BaseAgent):
    def __init__(self, id):
        super().__init__(id=id)
        
    def next_move(self, state):
        op_id = 1 if self.id == 2 else 2
        history = state['history']
        itr = state['current_iter']
        
        # On the first move, cooperate.
        if itr == 1:
            return 1
        
        # Check the last two moves of the opponent.
        last_move = history[-1][op_id]
        second_last_move = history[-2][op_id] if itr > 1 else 1
        
        # If the opponent has defected in the last two moves, defect as well.
        if last_move == -1 and second_last_move == -1:
            return -1
        
        # Otherwise, cooperate.
        return 1


In [161]:
from agent import BaseAgent
import random

class Agent(BaseAgent):
    def __init__(self, id):
        super().__init__(id=id)
        
    def next_move(self, state):
        op_id = 1 if self.id == 2 else 2
        itr = state["current_iter"]
        
        # On the first move, cooperate.
        if itr == 1:
            return 1
        
        # Retrieve the history of moves.
        history = state["history"]
        last_opponent_move = history[-1][op_id]
        
        # Implement forgiveness to account for potential misinterpretations.
        if itr > 2:
            second_last_opponent_move = history[-2][op_id]
            if last_opponent_move == -1 and second_last_opponent_move == -1:
                # Defect if the opponent has defected for the last two rounds.
                return -1
            else:
                # Otherwise, cooperate.
                return 1
        else:
            # If there's no history of the opponent defecting twice, cooperate.
            return 1


ModuleNotFoundError: No module named 'agent'